apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-config-secrets
  namespace: airbyte
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: airbyte-config-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-host
      remoteRef:
        key: airbyte-config-secrets #secret manager name 
        property: database-host
    - secretKey: database-port # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: database-port # ti comes from json of secret managr
    - secretKey: database-password # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: database-password 
    - secretKey: instance-admin-email # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: instance-admin-email
    - secretKey: instance-admin-password # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: instance-admin-password
    - secretKey: s3-access-key-id # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: s3-access-key-id
    - secretKey: s3-secret-access-key # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: s3-secret-access-key
    - secretKey: aws-secret-manager-access-key-id # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: aws-secret-manager-access-key-id
    - secretKey: aws-secret-manager-secret-access-key # this will be the content of the secret in k8s
      remoteRef:
        key: airbyte-config-secrets #secret manager name
        property: aws-secret-manager-secret-access-key
    
    
