apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets
type: Opaque
stringData:
  # Enterprise License Key

  database-host: "devrds.cfmmo0ocsk5d.ca-central-1.rds.amazonaws.com"
  database-port: "5432"
  database-name: "devrds"
  database-user: "devusers"
  database-password: "yourSuperSecretPassword123"

  instance-admin-email: nikhil.maddikunta@gov.bc.ca
  instance-admin-password: nikhil123

  # AWS S3 Secrets
  s3-access-key-id: ASIA4B7B5TYY3EGGNHAD
  s3-secret-access-key: spMNwrw2NHVz+cOHwlD75asNDHiNle53nn/Y4Zae

  aws-secret-manager-access-key-id: ASIA4B7B5TYY3EGGNHAD
  aws-secret-manager-secret-access-key: spMNwrw2NHVz+cOHwlD75asNDHiNle53nn/Y4Zae