postgresql:
  enabled: false

global:
  auth:
    enabled: true
    instanceAdmin:  
      secretName: "airbyte-config-secrets" 
      firstName: Nikhil
      lastName: Maddikunta
      emailSecretKey: "instance-admin-email"
      passwordSecretKey: "instance-admin-password"
  database:
    # Use external RDS instance and reference credentials via secret
    secretName: "airbyte-config-secrets"

    host: "devrds.cfmmo0ocsk5d.ca-central-1.rds.amazonaws.com"
    port: "5432"
    database: "devrds"
    user: "devusers"
    passwordSecretKey: "database-password"

  edition: community
  airbyteUrl: http://127.0.0.1:8080

  # auth:
  #   instanceAdmin:  
  #     firstName: Nikhil
  #     lastName: Maddikunta

  storage:
    type: "S3"
    bucket:
      log: airbytes3test
      state: airbytes3test
      workloadOutput: airbytes3test
    s3:
      region: ca-central-1
      authenticationType: instanceProfile

# webapp:
#   enabled: true
#   service:
#     type: LoadBalancer