postgresql:
  enabled: false

global:
  database:
    # Use external RDS instance and reference credentials via secret
    secretName: "airbyte-config-secrets"

    host: "devrds.cfmmo0ocsk5d.ca-central-1.rds.amazonaws.com"
    port: "5432"
    database: "devrds"
    user: "devusers"
    passwordSecretKey: "yourSuperSecretPassword123!"

  edition: community
  airbyteUrl: http://127.0.0.1:8080

  auth:
    instanceAdmin:  
      firstName: Nikhil
      lastName: Maddikunta

  storage:
    type: "S3"
    bucket:
      log: airbyte-pdems
      state: airbyte-pdems
      workloadOutput: airbyte-pdems
    s3:
      region: ca-central-1
      authenticationType: instanceProfile
