name: EKS Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::828865617457:role/github_oidc
          aws-region: ca-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TERRAFORM_DEV_BACKEND_BUCKET }}" \
            -backend-config="region=ca-central-1" \
            -backend-config="key=eks/${{ inputs.environment }}/terraform.tfstate" \
            -backend-config="dynamodb_table=terraform-lock" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file="env/${{ inputs.environment }}.tfvars" -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
